### ISSUE TITLE
[Validation] How do you reshape cpp_stft?

### ISSUE THREAD

**Issue by shreks7** [kooBH/STFT#12]
You have this line in the validation notebook - 
`cpp_stft = cpp_stft.reshape((int(len(cpp_stft)/514), 514))`

How do you get the number 514? 

Thank you!

**Comment by shreks7** [comment]
I tried the nearest divisor of `len(cpp_stft)` however then I get this error - 

```Traceback (most recent call last):
  File ".\plotTest.py", line 57, in <module>
    validateSTFT(inputAudioFile, inputBinaryFile)
  File ".\plotTest.py", line 41, in validateSTFT
    cpp_stft = cpp_stft[:,0::2] + cpp_stft[:,1::2]*1j
ValueError: operands could not be broadcast together with shapes (290,257) (290,256)```

**Comment by kooBH** [comment]
wav : [number_of_sample] -> stft[number_of_frame, n_hfft]  
n_hfft = (n_fft)/2 +1 

when n_fft = 512
n_hfft = 257
since STFT is in complex domian, view as double type array, stft[number_of_frame, 257*2] 

and in the memory sequence of data is : real imag real imag  
so, to convert into complex type ```cpp_stft[:,0::2] + cpp_stft[:,1::2]*1j```. And it seems one imaginary axis is missing.
